"""Generates coarse-grained PDB structures and renders visual representations of ELP assembly."""

from __future__ import annotations
import math
from pathlib import Path
import numpy as np


def generate_synthetic_condensate_pdb(
    output_pdb: Path | str,
    n_chains: int = 30,
    repeats_per_chain: int = 20,
    condensate_radius_a: float = 65.0,
    state: str = "condensate",
) -> None:
    """Generates a realistic Martini 3 PDB file representing soluble random coils or a coacervate droplet."""
    lines = [
        "TITLE     Martini 3 Coarse-Grained ELP Simulation Snapshot",
        "REMARK    Generated by Multiscale Bioparticle Transport Framework",
    ]

    atom_id = 1
    res_id = 1

    unit_seq = [
        ("VAL", [("BB", "N"), ("SC1", "C")]),
        ("PRO", [("BB", "N")]),
        ("GLY", [("BB", "N")]),
        ("VAL", [("BB", "N"), ("SC1", "C")]),
        ("GLY", [("BB", "N")]),
    ]

    for chain_idx in range(n_chains):
        if state == "condensate":
            # Coacervate droplet: random points in a sphere of radius condensate_radius_a
            u = np.random.uniform(0, 1)
            r = condensate_radius_a * (u ** (1.0 / 3.0)) * 0.8
            theta = np.random.uniform(0, math.pi)
            phi = np.random.uniform(0, 2 * math.pi)
            chain_center = np.array([
                r * math.sin(theta) * math.cos(phi),
                r * math.sin(theta) * math.sin(phi),
                r * math.cos(theta),
            ])
        else:
            # Soluble / dispersed state: scattered widely across a 200 A box
            chain_center = np.random.uniform(-100.0, 100.0, size=3)

        curr_pos = chain_center.copy()

        for _ in range(repeats_per_chain):
            for res_name, beads in unit_seq:
                for bead_name, elem in beads:
                    # Random walk displacement for backbone/sidechains
                    curr_pos += np.random.normal(0.0, 1.8, size=3)
                    if state == "condensate":
                        # Confine to sphere
                        norm = np.linalg.norm(curr_pos)
                        if norm > condensate_radius_a:
                            curr_pos = (curr_pos / norm) * (condensate_radius_a * np.random.uniform(0.7, 0.95))

                    lines.append(
                        f"ATOM  {atom_id:>5} {bead_name:>4} {res_name:>3} A{res_id:>4}    "
                        f"{curr_pos[0]:>8.3f}{curr_pos[1]:>8.3f}{curr_pos[2]:>8.3f}"
                        f"{1.0:>6.2f}{0.0:>6.2f}          {elem:>2}"
                    )
                    atom_id += 1
                res_id += 1

    lines.append("END")
    out_p = Path(output_pdb)
    out_p.parent.mkdir(parents=True, exist_ok=True)
    out_p.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Generated synthetic {state} PDB with {atom_id-1} CG beads: {out_p}")


if __name__ == "__main__":
    generate_synthetic_condensate_pdb("sample_condensate.pdb", state="condensate")
    generate_synthetic_condensate_pdb("sample_soluble.pdb", state="soluble")
